/**
 * Match utilities that are generated by matchUtilities function provided by TailwindCSS.
 * @example
 *
 * // Expected: true
 * matchUtiltiesRegex.test("animation-delay-100")
 *
 * // Expected: false
 * matchUtiltiesRegex.test("animation")
 */
export const matchUtilitiesRegex = new RegExp(/^(animation(?=Delay|Duration|Steps|IterationCount|FillMode|Range))/)

/**
 * Match utilities that are generated by addUtilities function provided by TailwindCSS.
 * @example
 *
 * // Expected: true
 * addUtilitiesRegex.test("animation")
 *
 * // Expected: false
 * addUtilitiesRegex.test("animation-delay-100")
 */
export const addUtilitiesRegex = new RegExp(/^(animation|keyframes|animationCubicBezier)/)

/**
 * Converts a camelCase string to a slash-case string.
 *
 * @param str - The camelCase string to transform.
 * @returns {string} - The transformed slash-case string.
 */
export const toSlashCase = (str: string): string => str.replace(/([A-Z])/g, "-$1").toLowerCase()
