import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { LayoutProps } from "@/lib/@types/props";
import { Header } from "@/ui/header/header";
import "@/ui/globals.css";
import { Footer } from "@/ui/footer";

const poppins = Poppins({ 
    subsets: ["latin"],
    weight: ["400", "500", "700"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased relative overflow-x-hidden bg-black scroll-smooth scroll:w-2 track:my-2 thumb:rounded thumb:bg-gray-100 has-[header.open]:scroll:bg-gray-300`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
